dataset_path: linbojunzi/Math
dataset_kwargs:
  token: True
task: "math"
test_split: train
output_type: generate_until
doc_to_visual: !function utils.math_doc_to_visual
doc_to_text: !function utils.math_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
# The return value of process_results will be used by metrics
process_results: !function utils.math_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: math_acc_score
    aggregation: !function utils.math_acc_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer the question using a single word or phrase."
  gpt4v:
    pre_prompt: ""
    post_prompt: "\nAnswer the question"
  qwen_vl:  
    pre_prompt: ""
    post_prompt: " Answer:"
metadata:
  - version: 0.0
